language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover ./build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
